#include <iostream>


using namespace std;

int main(){
	system("cls");
	short umur;
	int tgl;
	long long npm;
	float tb;
	double bb;
	string nama;
	char kelas;
	bool happy;
    char a = 177;
    char b = 219;
    cout << "\n\n\n\t\t\t\t     loading\n\n";
    cout << "\t\t\t\t";
    for (int i = 0;i <= 15;i++)
        cout << a;
    cout << "\r";
    cout << "\t\t\t\t";
    for (int i = 0;i <= 15;i++)
    {
        cout << b;
        for (int j = 0;j <= 1e8;j++);
    }
    cin.get();
	system("cls");
	cout << "==========================================================\n";
    cout << "||\t\t            BIODATA           \n";
    cout << "|| Masukan Nama Anda  \t\t\t: ";getline(cin>>ws,nama);
    cout << "|| Masukan Umur Anda \t\t\t: ";cin>>umur;
    cout << "|| Masukan Tanggal Lahir Anda (170205)  : ";cin>>tgl;
    cout << "|| Masukan NPM Anda \t\t\t: ";cin>>npm;
    cout << "|| Masukan Kelas Anda(1 Character)   \t: ";cin>>kelas;
    cout << "|| Masukan Tinggi Badan Anda    \t: ";cin>>tb;
    cout << "|| Masukan Berat Badan Anda    \t\t: ";cin>>bb;
    cout << "|| Apakah Anda Happy? (1/0)    \t\t: ";cin>>happy;
    cout << "==========================================================\n";
    cin.get();
	system("cls");
	cout<<"\n\t\t========Hallo!=======\n\n";
	cin.get();
	system("cls");
	cout<<"\n\t\t========Perkenalkan!=======\n\n";
	cin.get();
	system("cls");
	cout << "==========================================================\n";
    cout << "||\t\t            BIODATA           \n";
    cout << "|| Nama  \t\t\t: ";cout<<nama<<endl;
    cout << "|| Umur \t\t\t: "<<endl;
    cout << "|| Tanggal Lahir Anda (170205)  : "<<endl;
    cout << "|| NPM \t\t\t\t: "<<endl;
    cout << "|| Kelas Anda(1 Character)   \t: "<<endl;
    cout << "|| Tinggi Badan Anda    \t: "<<endl;
    cout << "|| Berat Badan Anda    \t\t: "<<endl;
    cout << "==========================================================\n";
	cin.get();
	system("cls");
	cout << "==========================================================\n";
    cout << "||\t\t            BIODATA           \n";
    cout << "|| Nama  \t\t\t: ";cout<<nama<<endl;
    cout << "|| Umur \t\t\t: ";cout<<umur<<endl;
    cout << "|| Tanggal Lahir Anda (170205)  : "<<endl;
    cout << "|| NPM \t\t\t\t: "<<endl;
    cout << "|| Kelas Anda(1 Character)   \t: "<<endl;
    cout << "|| Tinggi Badan Anda    \t: "<<endl;
    cout << "|| Berat Badan Anda    \t\t: "<<endl;
    cout << "==========================================================\n";
	cin.get();
	system("cls");
	cout << "==========================================================\n";
    cout << "||\t\t            BIODATA           \n";
    cout << "|| Nama  \t\t\t: ";cout<<nama<<endl;
    cout << "|| Umur \t\t\t: ";cout<<umur<<endl;
    cout << "|| Tanggal Lahir Anda (170205)  : ";cout<<tgl<<endl;
    cout << "|| NPM \t\t\t\t: "<<endl;
    cout << "|| Kelas Anda(1 Character)   \t: "<<endl;
    cout << "|| Tinggi Badan Anda    \t: "<<endl;
    cout << "|| Berat Badan Anda    \t\t: "<<endl;
    cout << "==========================================================\n";
    cin.get();
	system("cls");
	cout << "==========================================================\n";
    cout << "||\t\t            BIODATA          \n";
    cout << "|| Nama  \t\t\t: ";cout<<nama<<endl;
    cout << "|| Umur \t\t\t: ";cout<<umur<<endl;
    cout << "|| Tanggal Lahir Anda (170205)  : ";cout<<tgl<<endl;
    cout << "|| NPM \t\t\t\t: "<<npm<<endl;
    cout << "|| Kelas Anda(1 Character)   \t: "<<endl;
    cout << "|| Tinggi Badan Anda    \t: "<<endl;
    cout << "|| Berat Badan Anda    \t\t: "<<endl;
    cout << "==========================================================\n";
    cin.get();
	system("cls");
	cout << "==========================================================\n";
    cout << "||\t\t            BIODATA          \n";
    cout << "|| Nama  \t\t\t: ";cout<<nama<<endl;
    cout << "|| Umur \t\t\t: ";cout<<umur<<endl;
    cout << "|| Tanggal Lahir Anda (170205)  : ";cout<<tgl<<endl;
    cout << "|| NPM \t\t\t\t: "<<npm<<endl;
    cout << "|| Kelas Anda(1 Character)   \t: ";cout<<kelas<<endl;
    cout << "|| Tinggi Badan Anda    \t: "<<endl;
    cout << "|| Berat Badan Anda    \t\t: "<<endl;
    cout << "==========================================================\n";
    cin.get();
	system("cls");
	cout << "==========================================================\n";
    cout << "||\t\t            BIODATA           \n";
    cout << "|| Nama  \t\t\t: ";cout<<nama<<endl;
    cout << "|| Umur \t\t\t: ";cout<<umur<<endl;
    cout << "|| Tanggal Lahir Anda (170205)  : ";cout<<tgl<<endl;
    cout << "|| NPM \t\t\t\t: "<<npm<<endl;
    cout << "|| Kelas Anda(1 Character)   \t: ";cout<<kelas<<endl;
    cout << "|| Tinggi Badan Anda    \t: ";cout<<tb<<endl;
    cout << "|| Berat Badan Anda    \t\t: "<<endl;
    cout << "==========================================================\n";
    cin.get();
	system("cls");
	cout << "==========================================================\n";
    cout << "||\t\t            BIODATA           \n";
    cout << "|| Nama  \t\t\t: ";cout<<nama<<endl;
    cout << "|| Umur \t\t\t: ";cout<<umur<<endl;
    cout << "|| Tanggal Lahir Anda (170205)  : ";cout<<tgl<<endl;
    cout << "|| NPM \t\t\t\t: "<<npm<<endl;
    cout << "|| Kelas Anda(1 Character)   \t: ";cout<<kelas<<endl;
    cout << "|| Tinggi Badan Anda    \t: ";cout<<tb<<endl;
    cout << "|| Berat Badan Anda    \t\t: ";cout<<bb<<endl;
    cout << "==========================================================\n";
    cin.get();
	system("cls");
	if(happy == true){
	cout << "==========================================================\n";
    cout << "||\t\t            BIODATA           \n";
    cout << "|| Nama  \t\t\t: ";cout<<nama<<endl;
    cout << "|| Umur \t\t\t: ";cout<<umur<<endl;
    cout << "|| Tanggal Lahir Anda (170205)  : ";cout<<tgl<<endl;
    cout << "|| NPM \t\t\t\t: "<<npm<<endl;
    cout << "|| Kelas Anda(1 Character)   \t: ";cout<<kelas<<endl;
    cout << "|| Tinggi Badan Anda    \t: ";cout<<tb<<endl;
    cout << "|| Berat Badan Anda    \t\t: ";cout<<bb<<endl;
    cout << "|| Saya Bahagia Hari Ini ^_^ \n";
    cout << "==========================================================\n";
	}else{
	cout << "==========================================================\n";
    cout << "||\t\t            BIODATA           \n";
    cout << "|| Nama  \t\t\t: ";cout<<nama<<endl;
    cout << "|| Umur \t\t\t: ";cout<<umur<<endl;
    cout << "|| Tanggal Lahir Anda (170205)  : ";cout<<tgl<<endl;
    cout << "|| NPM \t\t\t\t: "<<npm<<endl;
    cout << "|| Kelas Anda(1 Character)   \t: ";cout<<kelas<<endl;
    cout << "|| Tinggi Badan Anda    \t: ";cout<<tb<<endl;
    cout << "|| Berat Badan Anda    \t\t: ";cout<<bb<<endl;
    cout << "|| Semoga Anda Menemukan Kebahagiaan Anda!!! ): \n";
    cout << "==========================================================\n";
	};
	cin.get();
	system("cls");
	cout<<"\n\t\t========Terima Kasih!=======\n\n";

}
